
ltcInfos = [
        {
            'userId': 1,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 1,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 1,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 2,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 2,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 2,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 2,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 2,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
        {
            'userId': 2,
            'fromDate': '2023-05-11',
            'toDate': '2023-05-20',
            'prefixFrom': None,
            'prefixTo': None,
            'suffixFrom': '2023-05-21',
            'suffixTo': '2023-05-22',
            'spouseEntitled': True,
            'earnedLeaveAvailed': 0,
            'natureOfTravel': 'home',
            'placeToVisit': 'dehradun',
            'totalEstimatedFare': 60000,
            'advanceRequired': False,
            'encashmentAvailed': False,
            'encashmentNoOfDays': 0,
            'stageRedirect': None,
            'stageCurrent': 1,
            'fillDate': '2023-05-08',
            'dateLog': {
                0: None,
                1: None,
                2: None,
                3: None,
                4: None,
                5: None,
                6: None,
                7: None,
                8: None,
                9: None,
                10: None,
                11: None,
                12: None,
                },
            'peopleInvolved': [
                {
                    'name': 'Tj',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                {
                    'name': 'Avi',
                    'age': 21,
                    'relation': 'gf',
                    'fromPlace': 'punjab',
                    'toPlace': 'dehradun',
                    'back': True,
                    'modeOfTravel': 'plane',
                    },
                ],
    },
    ]
