"""added sign url

Revision ID: 33e49d1e3f0a
Revises: 
Create Date: 2023-05-06 00:04:26.433980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e49d1e3f0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signUrl', sa.String(), nullable=True))

    op.execute("UPDATE users SET signUrl = false")
    op.alter_column('users', 'signUrl', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signUrl')

    # ### end Alembic commands ###
